"""add auto_suite table

Revision ID: 0c784180661e
Revises: 0684e3c62926
Create Date: 2023-09-26 19:16:30.231745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c784180661e'
down_revision: Union[str, None] = '0684e3c62926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_suite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduling_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('distro', sa.String(), nullable=True),
    sa.Column('distro_version', sa.String(), nullable=True),
    sa.Column('flavor', sa.String(), nullable=True),
    sa.Column('suite', sa.String(), nullable=True),
    sa.Column('log_path', sa.String(), nullable=True),
    sa.Column('cmd', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_suite_id'), 'auto_suite', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_suite_id'), table_name='auto_suite')
    op.drop_table('auto_suite')
    # ### end Alembic commands ###
